#!/usr/bin/env node
/**
 * 从 Apifox 导出的 OpenAPI URL 拉取并生成 TypeScript 类型。
 * 使用：APIFOX_OPENAPI_URL=https://... npm run openapi:sync
 */
import { execSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');
const outFile = join(root, 'src/types/generated-api.ts');
const url =
  process.env.APIFOX_OPENAPI_URL ?? process.env.VITE_OPENAPI_URL ?? '';

if (!url) {
  console.error(
    'Missing APIFOX_OPENAPI_URL (or VITE_OPENAPI_URL). Example:\n' +
      '  APIFOX_OPENAPI_URL=https://your-spec.json npm run openapi:sync',
  );
  process.exit(1);
}

mkdirSync(dirname(outFile), { recursive: true });
execSync(`npx openapi-typescript "${url}" --output "${outFile}"`, {
  cwd: root,
  stdio: 'inherit',
});

writeFileSync(
  join(root, 'src/types/generated-api.README.txt'),
  `This file is generated by npm run openapi:sync.
Source: ${url}
Do not edit generated-api.ts by hand.
`,
);

console.log('Wrote', outFile);
